require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'CameraKitExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'react-native-video', :path => '../../node_modules/react-native-video'
  pod 'RNSVG', :path => '../../node_modules/react-native-svg'
  pod 'react-native-cameraroll', :path => '../../node_modules/@react-native-community/cameraroll'
  pod 'RNScreens', :path => '../../node_modules/react-native-screens'
  pod 'RNGestureHandler', :path => '../../node_modules/react-native-gesture-handler'
  pod 'RNReanimated', :path => '../../node_modules/react-native-reanimated'

  
  pod 'react-native-image-filter-kit',:path => '../../node_modules/react-native-image-filter-kit'  
  pod 'react-native-safe-area-context', :path => '../../node_modules/react-native-safe-area-context'  
  pod 'ReactNativeAliAVKit', :path => '../..'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end
