require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'CameraKitExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'react-native-video', :path => '../../node_modules/react-native-video'
  pod 'RNSVG', :path => '../../node_modules/react-native-svg'
  pod 'react-native-cameraroll', :path => '../../node_modules/@react-native-community/cameraroll'
  pod 'RNGestureHandler', :path => '../../node_modules/react-native-gesture-handler'
  pod 'RNReanimated', :path => '../../node_modules/react-native-reanimated'
  pod 'RNCAsyncStorage', :path => '../../node_modules/@react-native-community/async-storage'

  pod 'react-native-image-filter-kit',:path => '../../node_modules/react-native-image-filter-kit'  
  pod 'ReactNativeAliAVKit', :path => '../..'
  pod 'react-native-image-editor', :path => '../../node_modules/@react-native-community/image-editor'
  
  pod 'RNPermissions', :path => "../../node_modules/react-native-permissions"
  permissions_path = '../../node_modules/react-native-permissions/ios'
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end
